# Generated by Django 2.1.5 on 2019-03-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phonenumber', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('fee_payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('fee', models.IntegerField(default=0)),
                ('event_venue', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('about', models.TextField()),
                ('cover', models.ImageField(upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(max_length=200)),
                ('subscriber_email', models.CharField(max_length=200)),
                ('subscriber_phonenumber', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinker.Event'),
        ),
    ]
