# Generated by Django 2.1.5 on 2019-03-10 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tinker', '0003_attendee_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 10, 7, 19, 42, 223690, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
