# Generated by Django 2.1.5 on 2019-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinker', '0004_subscriber_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
